version: '3.3'

services:
  client:
    image: maximir.jfrog.io/default-docker-virtual/2bebetter:latest
    depends_on:
      - api
    restart: unless-stopped
    ports:
      - "3000:3000"

  api:
    image: maximir.jfrog.io/default-docker-virtual/2bebetter-backend:latest
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=bebetter
      - POSTGRES_PORT=5432
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    ports:
      - "4000:4000"

  postgres:
    container_name: postgres
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: bebetter
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
